### ISSUE TITLE
🐞 Bug: gollama ignores editor parameter

### ISSUE THREAD

**Issue by marcin-github** [sammcj/gollama#130]
## Description
gollama ignores both env variable and also setting in config file:
```
jq '.editor' config.json
"/usr/bin/nano"
```

## Environment

- OS and version: ubuntu 22.04
- Install source: ```gollama -v
v1.27.17
``` installed using `go install github.com/sammcj/gollama@1.27.17`
- Go version: ```$ go version
go version go1.18.1 linux/amd64
```

## Can you contribute?

- [ ] I will attempt to implement a fix for this bug

<!-- It's ok if not, but it's always great to have contributors! -->

**Comment by sammcj** [comment]
Thanks for reporting this, I'll investigate :)

**Comment by sammcj** [comment]
@marcin-github the release that's being built now should fix this for you.

Sorry about how long it took me to get round to this - busy week! 😅
