### ISSUE TITLE
🐞 Bug: go install "command not found"

### ISSUE THREAD

**Issue by stanthewizzard** [sammcj/gollama#132]
Hello

On a mac (mac M4pro Sequoia)

brew install go

then go install github.com/sammcj/gollama@HEAD

gollama command not found

Is this a bug or me ?
Thanks

**Comment by sammcj** [comment]
Hey there,

I'd be willing to bet your path is incorrectly setup, does it include `$home/go/bin`?

**Comment by sammcj** [comment]
If not (and you restarted your shell after installing go) - it sounds like a bug in the homebrew go package.

Part of installing go should create a $home/go/bin directory and update your path to include it.

**Comment by stanthewizzard** [comment]
right
And now there is a new issu with pinokio

Error fetching models:
- Error: ENOENT: no such file or directory, stat '/Users/stanislask/pinokio/api/tags'
- Configured API URL: http://0.0.0.0

:/

**Comment by sammcj** [comment]
echo $OLLAMA_HOST

**Comment by stanthewizzard** [comment]
Return nothing :(

**Comment by sammcj** [comment]
Normally $OLLAMA_HOST is set to the URL of your ollama instance, e.g. `http://localhost:11434`

**Comment by stanthewizzard** [comment]
I have nothing. Install wit dmg from ollama site

**Comment by sammcj** [comment]
It looks like you're trying to connect to ollama on port 80, but it runs on 11434?

> 0.0.0.0:80

**Comment by stanthewizzard** [comment]
I'm only launching gollama

**Comment by stanthewizzard** [comment]
On mac
launchctl setenv OLLAMA_HOST "0.0.0.0:80"
and then ./gollama

It's working

How to change gollama listening port to 11434 ?

thanks

**Comment by sammcj** [comment]
Hi Stan,

Gollama checks for Ollama listening on port 11434 by default (see https://github.com/sammcj/gollama/blob/a8fb3a52468849dc89f938d821f98ea53fa75790/config/config.go#L53-L54)

It will only check for other hosts or non-standard ports if you set one in OLLAMA_HOST, OLLAMA_API_URL or in your ~/.config/gollama/config.json file.

**Comment by sammcj** [comment]
Is your Ollama actually listening on 11434? Because if setting OLLAMA_HOST to :80 worked that suggests it's not.

```
lsof -i :11434
COMMAND   PID USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
ollama  22343 samm    3u  IPv4 0x2d5c10a066bc49c      0t0  TCP localhost:11434 (LISTEN)
```

**Comment by stanthewizzard** [comment]
if I don't use (I used it for testing onlu)
`launchctl setenv OLLAMA_HOST "0.0.0.0:80"`
it listen on 11434
on the mac there is only this directive
`launchctl setenv OLLAMA_HOST "0.0.0.0"`

There is an issue on y mac with gollama

**Comment by sammcj** [comment]
I think Ollama should be fine with IPv6, but by default I believe it only listens on v4.

I would not recommend trying to run Ollama on port 80 as that's a reserved port that will likely require root privileges to listen on.

If you open a fresh terminal session and type `echo $OLLAMA_HOST` - what does it return?

If you close Ollama, `export OLLAMA_HOST=localhost:11434` and then run `ollama serve` - does Gollama connect to it?

Either way - I think this is a problem with the way you're running Ollama.

**Comment by stanthewizzard** [comment]
echo $OLLAMA_HOST
0.0.0.0

export OLLAMA_HOST=localhost:11434
localhost:11434

launching ./gollama
Error fetching models:
- Error: Get "http://0.0.0.0/api/tags": dial tcp 0.0.0.0:80: connect: connection refused
- Configured API URL: http://0.0.0.0

BUT
./gollama -H
WORKS

some lines are white though

**Comment by sammcj** [comment]
I can't replicate this sorry, I suspect it's a user / OS configuration issue. Feel free to submit a PR if you find it to be a code issue and have an idea.

**Comment by stanthewizzard** [comment]
I can on 2 mac. 
Not a big deal
Thank you for your time
