### ISSUE TITLE
🐞 Bug: failed to write config file [Windows 11]

### ISSUE THREAD

**Issue by otravers** [sammcj/gollama#135]
## Description

I get this error message after running Gollama:

Error loading config: failed to create default config: failed to write config file: Config File "C:\\Users\\Owner\\.config\\gollama\\config.json" Already Exists

## How to reproduce

- Install Gollama on Windows 11 via go method
- Launch it from the command line

## Environment

- Windows 11
- Install source: Go get
- Go version: go1.23.2 windows/amd64

## Can you contribute?

- [ ] No, sorry!

**Comment by sammcj** [comment]
Hello, Sorry Gollama is not supported on Windows, it's designed as a Linux/macOS tool and I have no way to test windows workarounds / compatibility.
