### ISSUE TITLE
🐞 Bug: UI: Some menu tables are misaligned

### ISSUE THREAD

**Issue by vt-alt** [sammcj/gollama#136]
## Description

Some views have misaligned table and table captions.

## How to reproduce + Screenshots / Logs
1.
```
builder@x86_64:~/RPM/BUILD/gollama-1.27.20$ ./gollama -l
Name                                                                    Size       Quant      Family         Modified   ID
codellama:code                                           3.56GB Q4_0   llama 2024-11-08 8df0a30
llama3.2:1b                                              1.23GB Q8_0   llama 2024-10-09 baf6a78
llama3.2:latest                                          1.88GB Q4_K_M llama 2024-10-09 a80c4f1
llama3:latest                                            4.34GB Q4_0   llama 2024-06-20 365c0bd
```
Note that `Size` is not above size column.
Even on [README screenshot](https://github.com/sammcj/gollama/blob/main/screenshots/cli-list.jpg) `Size Quant Family` table headings are misaligned.

2. Plain gollama run:
```
   Ollama Models

  4 items

▐ codellama:code                                                         3.56GB      Q4_0        llama           2024-11-08  8df0a30
llama3.2:1b                                                             1.23GB      Q8_0        llama           2024-10-09  baf6a78
llama3.2:latest                                                         1.88GB      Q4_K_M      llama           2024-10-09  a80c4f1
llama3:latest                                                           4.34GB      Q4_0        llama           2024-06-20  365c0bd
```
The line with ▐ cursor is shifted right 2 chars (well, maybe this one is intended).

## Environment

- Linux distribution: ALT Linux
- Install source: go build
- Go version: `go version go1.23.3 linux/amd64`

## How did you find out about Gollama?

GitHub Explore recommended `Based on repositories you’ve viewed`.

**Comment by sammcj** [comment]
Thanks I've been meaning to fix this for quite some time, just needed a push 😅.
Just pushed out a fix. It'll be available after the builds are finished.

**Comment by vt-alt** [comment]
Thank you!

**Comment by mikaeloduh** [comment]
Is this fixed? I checked with v1.28.8 and it's still the same.

**Comment by sammcj** [comment]
Haven't noticed any issues with misalignment since the PR?

<img width="1522" alt="Image" src="https://github.com/user-attachments/assets/a6dc16be-286a-49e2-9f45-bfb3e54e939e" />

**Comment by mikaeloduh** [comment]
It looks good when running `gollama -l`, but running `gollama` without arguments still shows misalignment.

**Comment by sammcj** [comment]
Looks the same for me:

<img width="1541" alt="Image" src="https://github.com/user-attachments/assets/5dfb4977-5a2f-4618-8d27-f2365763b830" />

**Comment by mikaeloduh** [comment]
The line with does not align with the columns of the other lines
![Image](https://github.com/user-attachments/assets/3d0beae5-670b-41c6-aaf6-e21cea2b7745)

**Comment by sammcj** [comment]
That's by design - you've got that row selected, so it shows which item you're on
