### ISSUE TITLE
🐞 Bug: config,json Already Exists

### ISSUE THREAD

**Issue by EntropyYue** [sammcj/gollama#138]
in Windows, If I modify config.json, it will prompt me 
Error loading config: failed to create default config: failed to write config file: Config File "C:\\Users\\user\\.config\\gollama\\config.json" Already Exists

**Comment by sammcj** [comment]
Hey there, thanks for logging an issue.

Gollama isn't supported on Windows, but I've just pushed a small change that might resolve this for you. Once the [build](https://github.com/sammcj/gollama/actions/runs/12020217164) is complete you can update Gollama and give it a try.

**Comment by sammcj** [comment]
This should hopefully be resolved now.
