### ISSUE TITLE
🐞 Bug: redraw screen after exiting help

### ISSUE THREAD

**Issue by angstwad** [sammcj/gollama#145]
## Description

After opening help (`h`) and hitting `esc` or `q`, the terminal doesn't redraw the screen, help remains open, and you have to quit and re-open to get back to the main view.

## How to reproduce

1. Start `gollama`
2. Use help w/ `h`
3. Exit help (`esc` or `q`)

## Environment

- macOS version: 5.2
- Install source: go install from git head
- Go version: go version go1.23.2 darwin/arm64

## Can you contribute?

Potentially...

**Comment by sammcj** [comment]
Thanks for taking the time to log this bug report.

I'll have a look at this (and some other redraw issues) early in the new year. I suspect I'm over-complicating the redraw/refresh code in a number of places.

**Comment by sammcj** [comment]
Actually - that was an easy fix! New build incoming - https://github.com/sammcj/gollama/pull/146
