### ISSUE TITLE
pressing c to copy doesn't work on my machine

### ISSUE THREAD

**Issue by technovangelist** [sammcj/gollama#17]
on a m1 max mac book pro. I think the rest works.

awesome tool

**Comment by technovangelist** [comment]
scratch that... copy, delete, and update are broken....still awesome though

**Comment by sammcj** [comment]
Ruh Roh! Not very good of my to release new features with broken keybindings 😂, they were working … at some point - so I’ll have a look at this later in the weekend.

Cheers for the YouTube shout out as well!

**Comment by sammcj** [comment]
New build is just running now @technovangelist, hopefully it fixes this issue although I'll rewrite the hotkeys in the near future - they're too complicated for ... just ... keys 😅

**Comment by sammcj** [comment]
Is the latest build working for you now @technovangelist ?

**Comment by sammcj** [comment]
99% sure this is resolved now.

**Comment by technovangelist** [comment]
yes it works, but after the copy the list isn't updated to show the new model

**Comment by sammcj** [comment]
Should be fixed in release building now.
