### ISSUE TITLE
Can not run when enter using docker container

### ISSUE THREAD

**Issue by meicale** [sammcj/gollama#20]
When use the docker container to run the ollama, it cannot run it directly. Add the support for using docker container or some config options. I think a simple alias should work. Thank you!

**Comment by sammcj** [comment]
Oh yes, should be easy enough, will do.

**Comment by sammcj** [comment]
@meicale added some initial support for running without a local Ollama client when you have Ollama running in a container.

See https://github.com/sammcj/gollama/releases/tag/v1.8.0

After running the new version once, in your config file you should have a new item `"docker_container"`, if you set it's value to the name of your ollama container, it should (hopefully) run the Ollama run command inside the container.

Let me know how it goes.
