### ISSUE TITLE
Add more to inspect

### ISSUE THREAD

**Issue by technovangelist** [sammcj/gollama#21]
I wish inspect also showed me more about the model file. The prompt and system prompt and Params. And from there allow me to press u to edit it would be amazing

**Comment by sammcj** [comment]
Totally agree, I still have https://github.com/sammcj/gollama/issues/7#issuecomment-2145400748 open for this reason - I've just updated it's description with my notes, is there anything else you'd see value in having as part of that or as a stretch goal?

**Comment by sammcj** [comment]
![image](https://github.com/sammcj/gollama/assets/862951/65cd1fb4-16ee-491c-96c2-35205f1dbf6b)

**Comment by sammcj** [comment]
Going to close this issue off and track the remaining item (edit params from inspect) in https://github.com/sammcj/gollama/issues/7
