### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fahdmirza** [sammcj/gollama#4]
Getting Following error, while running:

(gollama) Ubuntu@0055-kci-prxmx10068:~/gollama$ ./gollama
Loading config from: /home/Ubuntu/.config/gollama/config.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x24 pc=0x4e45f4]

goroutine 1 [running]:
log.(*Logger).output(0xc0001266f8?, 0x4c4b32?, 0xc0001266f8?, 0x4c625e?)
        /usr/local/go/src/log/log.go:203 +0x34
log.(*Logger).Println(0x8547e0?, {0xc000126860?, 0x854700?, 0xa68960?})
        /usr/local/go/src/log/log.go:276 +0x4b
github.com/sammcj/gollama/config.LoadConfig()
        /home/Ubuntu/gollama/config/config.go:45 +0x278
main.main()
        /home/Ubuntu/gollama/main.go:41 +0x78

(gollama) Ubuntu@0055-kci-prxmx10068:~/gollama$ go version
go version go1.22.3 linux/amd64

(gollama) Ubuntu@0055-kci-prxmx10068:~/gollama$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
(gollama) Ubuntu@0055-kci-prxmx10068:~/gollama$

**Comment by sammcj** [comment]
Interesting, I've only tested on macOS thus far, but will look into this and get back to you!

Thanks for logging the bug.

**Comment by sammcj** [comment]
found the problem, fix coming soon

**Comment by sammcj** [comment]
@fahdmirza just pushed a fix, can you please let me know if that works for you now?

**Comment by fahdmirza** [comment]
> @fahdmirza just pushed a fix, can you please let me know if that works for you now?

Thanks, works now. I also created an installation video on my channel . Feel free to add it to your repo. Thanks.      https://youtu.be/24yqFrQV-4Q

**Comment by sammcj** [comment]
Wow that's so cool! Thank you so much Fahd.
