### ISSUE TITLE
Feat: Add to homebrew

### ISSUE THREAD

**Issue by sammcj** [sammcj/gollama#51]
It would be nice for folks to be about to install gollama with a simple `brew install gollama` 

**Describe the solution you'd like**

- add to homebrew (or via a tap)

https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by DanzigerGeist** [comment]
@sammcj PR opened: https://github.com/Homebrew/homebrew-core/pull/178405

**Comment by sammcj** [comment]
Oh legend! Thank you!

**Comment by sammcj** [comment]
@DanzigerGeist looks like they're waiting on some changes on your PR

**Comment by abitrolly** [comment]
It is done. Here https://github.com/Homebrew/homebrew-core/pull/189888

**Comment by sammcj** [comment]
Oh I missed this! Thank you! 🎉

**Comment by mikaeloduh** [comment]
This should be included in the README.
