### ISSUE TITLE
Request feature: push to registry

### ISSUE THREAD

**Issue by mann1x** [sammcj/gollama#6]
Would be nice to have, like delete, an option to push to the registry the selected models.

1. Ideally following the order used to select them or asking to-reorder before publishing.

1. Summary at then to know the outcome

**Comment by sammcj** [comment]
Thanks for logging this, it's actually already in my list of TODOs!

I really should add all my ideas to Github issues - I only just wrote this tool yesterday so it's in it's very early stages 😅

**Comment by mann1x** [comment]
Nice!
Even a short list in the README would do the job fine for a start 😄

**Comment by sammcj** [comment]
@mann1x it's _bound_ to have a few bugs, but added push (and copy)
