### ISSUE TITLE
⭐️ Feat:  Any chance this app can run on windows

### ISSUE THREAD

**Issue by ALBIHANY** [sammcj/gollama#62]
Hi is there any change this app can run on windows cmd such as Power shell ? i couldn't find any information about, it will really be great if that is possible.

Thank you

![winver](https://github.com/sammcj/gollama/assets/4164766/d03542ce-59cc-40de-9e0d-de6cba01629d)

**Comment by ALBIHANY** [comment]
Never mind just got it to work with power shall

![image](https://github.com/sammcj/gollama/assets/4164766/74a73df1-54b6-44b0-8831-0a9a350086fc)

**Comment by sammcj** [comment]
Hey, Sorry I don't run windows anywhere so I'm not planning on adding official support. Great to see it works in powershell for you though!

**Comment by umutdr** [comment]
@ALBIHANY, how did you manage to make it run on Windows? A guide would be nice.

**Comment by ALBIHANY** [comment]
> [@ALBIHANY](https://github.com/ALBIHANY), how did you manage to make it run on Windows? A guide would be nice.

Hey just run the same commands on windows PowerShell it's technically i Linux terminal on windows everything works the same with no modification needed at all
