### ISSUE TITLE
Feat: Model inspector

### ISSUE THREAD

**Issue by sammcj** [sammcj/gollama#7]
- ✅ Name
- ✅ Size (GB)
- ✅ Quant
- ✅ Family
- ✅ Modified
- ✅ ID 
- ✅ Parameters
- Prompt template - tracking in https://github.com/sammcj/gollama/issues/46
- System prompt - tracking in https://github.com/sammcj/gollama/issues/46
- Path on disk - tracking in https://github.com/sammcj/gollama/issues/46
- Ability to edit (update) individual parameters/template items - tracking in https://github.com/sammcj/gollama/issues/46

If the model is present on the same machine as gollama, there could also be the possibility of looking at the GGUF metadata for some additional effort.

**Comment by sammcj** [comment]
basic model inspection is now there, would be good to get some gguf metadata in there next

**Comment by sammcj** [comment]
Added Modelfile parameters to inspect:

<img width="651" alt="SCR-20240609-theu" src="https://github.com/sammcj/gollama/assets/862951/99fbbb7b-69f4-4a9f-9dfc-28c32b84517d">

Note that this only currently works if the ollama client is available (running with ollama client inside a container will be fixed in #20)

**Comment by technovangelist** [comment]
this will be great.

**Comment by sammcj** [comment]
Inspector is working nicely for the most part, tracking new in-place editing functionality in https://github.com/sammcj/gollama/issues/46

**Comment by ibagur** [comment]
Hi, is it possible to get also the number of parameters of a given model? For example, when using `ollama show phi4:latest` I usually get the number of parameters for that model (14B in this case). I am asking this because sometimes a default model is named 'model:latest' and there is not direct indication on the number of parameters that model has:
```
    architecture        phi3
    parameters          14.7B
    context length      16384
    embedding length    5120
    quantization        Q4_K_M

```

I have not been able to see it with `gollama`. On the other hand it outputs a lot of detailed information, which is great.

**Comment by sammcj** [comment]
Hmmm, I think it would be possible for certain with models available on the local machine (as I can use the GGUF metadata), I'm not sure if Ollama's API exposes this but I'll create a new issue to look into this.

Note: I'm nothing short of insanely busy with work at the moment so ollama development is a little slower than usual while I catch up.

**Comment by sammcj** [comment]
Created https://github.com/sammcj/gollama/issues/177
